name: Deploy application to production

on:
  push:
    branches:
      - 'main'  # production branch

jobs:
  build:
    runs-on: ubuntu-latest
    # See https://quay.io/repository/hypernode/deploy?tab=tags for all possible tags.
    container: quay.io/hypernode/deploy:latest-php8.3-node22
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-composer
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: hypernode-deploy build -vvv
    - name: archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deployment-build
        path: build/build.tgz
        retention-days: 7
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Concurrency takes any arbitrary value, but this prevents multiple deployments happening at the same time.
    # We set the concurrency to production for this deployment workflow.
    concurrency: production
    environment:
      name: production
      url: https://hntestdemian.hypernode.io
    container: quay.io/hypernode/deploy:latest-php8.3-node22
    steps:
    - uses: actions/checkout@v3
    - name: download build artifact
      uses: actions/download-artifact@v3
      with:
        name: deployment-build
        path: build/
    - uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-composer
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: mkdir -p $HOME/.ssh
    - run: hypernode-deploy deploy production -vvv  # Deploy production stage defined in deploy.php
